all: copiar pipes-bandwidth

copiar: copiar.cpp
	g++ -o copiar -O3 copiar.cpp

pipes-bandwidth: pipes-bandwidth.cpp
	g++ -o pipes-bandwidth -O3 pipes-bandwidth.cpp

clean:
	rm -f copiar pipes-bandwidth
